### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by KeyJoo** [RadugaCamp/diventello#13]
# Tools

## Chart-flow /Mapping/

- https://realtimeboard.com
- https://te-st.ru/entries/whimsical-tool/amp/
- https://whimsical.co/flowcharts/

**Comment by vovs03** [comment]
# Tools / Environment

- Nodejs
  - `sudo apt-get install nodejs`
- Npm
  - `sudo apt install npm`
- https://cordova.apache.org/docs/ru/latest/guide/platforms/android/index.html
- Android Studio
- Android SDK
- Android JDK
- http://framework7.io/templates/
- https://yarnpkg.com/en/docs/cli/run

## Versioning

- #42

## Extended

- WEBPACK
- GULP
- https://github.com/pugjs
