### ISSUE TITLE
Prepare text songs stage

### ISSUE THREAD

**Issue by KeyJoo** [RadugaCamp/diventello#35]
# Preparing-text-songs-stage.md

## ToDo

- clean spaces
- ~~Unificate Songs names: name.txt -> Name.txt~~ (Approved)
- Change letter: "е" >> "ё"
- input space in starts: "1.Начиная..." >> "1. Начиная..."
- Fix **reprize** like _//: some text ://_

## stages in progress

| Stage | Songs | Date complete |
| :-:|-|:-:|
|4|[x] 31-40| (2018-08-13)|
|5|[ ] <mark>41-50</mark>| (2018-08-14)|
|6|[ ] 51-60| (2018-08-)|
|7|[ ] 61-70| (2018-08-)|
|8|[ ] 71-80| (2018-08-)|
|9|[ ] 81-90| (2018-08-)|
|10|[ ] 91-100| (2018-08-)|

## Stages [16]

-  [ ] 1 1-10
-  [ ] 2 11-20
-  [ ] 3 21-30
-  [x] 4 31-40
-  [ ] 5 41-50
-  [ ] 6 51-60
-  [ ] 7 61-70
-  [ ] 8 71-80
-  [ ] 9 81-90
-  [ ] 10 91-100
-  [ ] 11 101-110
-  [ ] 12 111-120
-  [ ] 13 121-130
-  [ ] 14 131-140
-  [ ] 15 141-150
- [ ] 16 151-...152?

**Comment by nanomen** [comment]
Круто Вова, но я бы не советовал название файла перегонять с заглавной буквы - т.к. консистентность обработки имени файла теряется. Все равно при работе с файлом, придется в строчные переводить - toLoverCase.

**Comment by KeyJoo** [comment]
@nanomen , спасибо за ценное замечание!!! 
Поглядывай, где я делаю что-то не в том направлении.
Этот [вариант](https://github.com/RadugaCamp/diventello/commit/4865634b76ad73647264f83d533553001af8e62a) #39 был выбран, т.к. ещё не разобрался, как пользоваться динамическими роутами. Это бы сильно облегчило работу со списком ;)
