### ISSUE TITLE
Выбор стека / языка под платформу.

### ISSUE THREAD

**Issue by KeyJoo** [RadugaCamp/diventello#8]
# Platform: Language & ecosystem

## Crossplatform:

- 

## Android:

- Java / Kotlin
- VueJS / TypeScript

## iOS

- Swift

**Comment by KeyJoo** [comment]
# Linux > Framework7

- LinuxTry Android Studio > Problems with emulator (Android components)
- Install IntellijIDEA Community 2018.2 (JetBrains) < It works!

**Comment by vovs03** [comment]
# Preparing:

- [x] Install Android Studio
- [x] Install Android SDK
- [ ] Install Android JDK from https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html My variant:

Linux | 147.28 MB | [jdk-11.0.2_linux-x64_bin.deb](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html)
-- | -- | --

- `cordova requirements` - :warning: Check it!

- :mega:  `sudo apt install gradle` 119Mb  
- [ ] Install Cordova
- [x] Create Framework7 project (Cordova + FR7 + Webpack + Vuejs )

**Comment by KeyJoo** [comment]
В итоге я начал проект на основе: (Cordova + FR7 + Webpack + Vuejs )
